name: front
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev, which is a good practice for private apps.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Ensure that you are using the latest versions of your dependencies
  # or the versions that best suit your project needs.
  path_provider: ^2.1.1
  file_picker: ^6.1.1
  sqflite: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  # The test package is usually used for Dart packages or Flutter applications
  # to write and run tests. Ensure you have the correct version.
  test: ^1.24.3
  # Mockito is used for mocking in tests. Ensure you are using a compatible version.
  mockito: ^5.4.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/rocket.png

# The flutter_intl section below enables internationalization support
# using the IntelliJ plugin for Flutter Intl. It is configured correctly
# if you are using this plugin.
flutter_intl:
  enabled: true
